- hosts: balancer
  become: yes
  tasks:
  - name: Garantindo o HAProxy
    package:
      name: haproxy
      state: present
  - name: Garantindo a configuração
    copy:
      src: haproxy.cfg
      dest: /etc/haproxy/
  - name: Garantindo o serviço HAProxy
    service:
      name: haproxy
      state: restarted
      enabled: yes
